<?php
/**
 * Created by PhpStorm.
 * User: Olga
 * Date: 23.10.2016
 * Time: 14:11
 */

namespace App\Http\Controllers;


class SocialAuthControllerTest extends \TestCase
{
    public function setUp()
    {
        parent::setUp();

    }

    public function test()
    {
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


}
